### ISSUE TITLE
when i am implementing  people picker in spfx the suggestions are coming on the top left corner? please help

### ISSUE THREAD

**Issue by prabhat9999** [giuleon/SPFx-OfficeUIFabric-PeoplePicker#4]
![40847204-0552153c-65bc-11e8-8888-2e0e804b537b](https://user-images.githubusercontent.com/36052078/40887220-8a50f49e-6745-11e8-937d-220d5d08c40b.png)

**Comment by giuleon** [comment]
Please check if you have some CSS conflict so some classes are overwritten

**Comment by giuleon** [comment]
No updates on this one I'll close it
